In [1]:
import numpy as np

In [3]:
an_array=np.array([333,444,555])    #create 1st rank array

In [4]:
print(type(an_array))

<class 'numpy.ndarray'>


In [5]:
an_array.shape             #test the shape of array it has just one dimension

(3,)

In [6]:
print(an_array[0],an_array[1],an_array[2])

333 444 555


In [7]:
an_array[1]=222                                  # numpy arrays are mutable

In [8]:
print(an_array[0],an_array[1],an_array[2])

333 222 555


In [9]:
an_array2=np.array([[333,444,555]])

In [10]:
an_array2.shape


(1, 3)

In [11]:
another = np.array([[1,2,5],[4,3,6]])

In [11]:
another


array([[1, 2, 5],
       [4, 3, 6]])

In [12]:

print("shape is in rows and columns",another.shape,"resp.")

shape is in rows and columns (2, 3) resp.


In [13]:
print("element at [0,0]",another[0,0],"\nelement at [0,1]",another[0,1],"\nelement at [1,0]",another[1,0])

element at [0,0] 1 
element at [0,1] 2 
element at [1,0] 4


In [13]:
#creating 2X2 array containing zero
ex1=np.zeros((3,3))

In [14]:
ex1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
#declare matrix filled with particular value
ex2=np.full((3,3),2.0)
ex2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [16]:
#matrix that contain diagonally one
ex3=np.eye(3,3)
ex3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
ex4 = np.ones((3,3))    #creating array with valuue ones
ex4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ex4[1,0]

1.0

In [20]:


ex4.shape    #ex4 array rank 2 array i.e 2X1

(3, 3)

In [19]:
# which means we need to use two indexes to access the element

print(ex4[0,0])



1.0


In [54]:
ex4[1,0]

1.0

In [20]:
ex4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
print("three rows and three column\n",ex4.shape)

three rows and three column
 (3, 3)


In [21]:
# generate 3X3 matrix with random float values between 0 and 1

ex5 = np.random.random((2,1))
ex5

array([[0.25598853],
       [0.0545607 ]])

In [22]:
an_array = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
an_array

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

# rows, column
# e.g. 4 : 6, 2:4
# 4th and 5th rows, 2nd and 3rd columns


In [23]:
print(an_array[0:2,2:4])   #[rows range - select 0,1,2 values , columns range - select 1 value only]

[[13 14]
 [23 24]]


In [24]:
a_slice= an_array[0:2,1:3]
a_slice

array([[12, 13],
       [22, 23]])

In [25]:
print("before:",an_array[0,1])     #inspect the element at 0,1
a_slice[0,0]=1000                   # a slice is same piece of data as an_array[0,0]
print("after: ",an_array[0,1])

before: 12
after:  1000


In [26]:
an_array

array([[  11, 1000,   13,   14],
       [  21,   22,   23,   24],
       [  31,   32,   33,   34]])

In [26]:
a_slice

array([[1000,   13],
       [  22,   23]])

In [27]:
#create rank 2 array of shape (3,4)
an_array = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])

an_array

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [28]:



#using both integer indexing and slicing generates an array of lower rank
row_rank1=an_array[1, :]        #rank 1 view
print(row_rank1,row_rank1.shape)    # notice only a single []

[21 22 23 24] (4,)


In [28]:
#slicing alone: generates an array of the same rank as the ann_array
row_rank2=an_array[1:2 , :]        #rank 2 view
print(row_rank2,row_rank2.shape)    #notice []

[[21 22 23 24]] (1, 4)


In [29]:
col_rank1 = an_array[:,2]
print(col_rank1,col_rank1.shape)

[13 23 33] (3,)


In [30]:
col_rank2 = an_array[:,1:3]
print(col_rank2,col_rank2.shape)

[[12 13]
 [22 23]
 [32 33]] (3, 2)


In [31]:
an_array =np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])
print("\nOriginal array: ")
print(an_array)                   


Original array: 
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [33]:
#creating array indices
col_indices =np.array([0,1,2,0])
print("\ncol indices picked: ",col_indices)
row_indices=np.arange(4)                          #arrange will select (0,1,2,3)
print("\nrow indices picked: ",row_indices)


col indices picked:  [0 1 2 0]

row indices picked:  [0 1 2 3]


In [34]:
#examine the pairing of row_indices and col_indices. 
for i,j in zip (row_indices,col_indices):
    print(i, ",",j)
'''for i in row indices
     for j in column indices'''

0 , 0
1 , 1
2 , 2
3 , 0


'for i in row indices\n     for j in column indices'

In [35]:
#select on element from each row
print('Values in the array at those indices: ',an_array[row_indices,col_indices])
#an_array[0,0],an_array[1,1],an_array[2,2],an_array[3,0] =an_array[row_indices,col_indices]



Values in the array at those indices:  [11 22 33 41]


In [36]:
#change one element from each row using indices selected
an_array[row_indices,col_indices] +=10000       #a= a+10000 same as a+=10000
print("\nchange array: ")
print(an_array)


change array: 
[[10011    12    13]
 [   21 10022    23]
 [   31    32 10033]
 [10041    42    43]]


In [37]:
#creating 3x2 array
an_array=np.array([[23,4,34],[45,11,15],[56,27,48]])
print(an_array)


[[23  4 34]
 [45 11 15]
 [56 27 48]]


array([48, 23, 11, 48])

In [37]:
filter = an_array<40      #creating filter which having boolean values depend on comparison operator
filter

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False],
       [False, False, False]])

In [38]:
print(an_array[filter])      # we can show only those elements which are meeting our criteria i.e filter

[12 13 21 23 31 32]


In [39]:
print(an_array[an_array<40])      #we can directly use criteria in square bracket the results are same as above

[12 13 21 23 31 32]


In [40]:
an_array[an_array%2==0]+=100

In [41]:
an_array

array([[10011,   112,    13],
       [   21, 10122,    23],
       [   31,   132, 10033],
       [10041,   142,    43]])

In [42]:
a = [2, 3, 6, 7, 8, 9]
print(a[2:4])

[6, 7]


In [82]:
array =np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]]) 
print(array[1:3,2:4])

[[23 24]
 [33 34]]


In [83]:
array


array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [45]:
#array[0:1,0:1]="32"

In [85]:
array

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

# Reading each element in matrix with for loop

In [84]:
for i in range (4):
    for j in range(3):
        print("this is",j,"th row and",i,"th column element, value is: ",array[j,i])

this is 0 th row and 0 th column element, value is:  11
this is 1 th row and 0 th column element, value is:  21
this is 2 th row and 0 th column element, value is:  31
this is 0 th row and 1 th column element, value is:  12
this is 1 th row and 1 th column element, value is:  22
this is 2 th row and 1 th column element, value is:  32
this is 0 th row and 2 th column element, value is:  13
this is 1 th row and 2 th column element, value is:  23
this is 2 th row and 2 th column element, value is:  33
this is 0 th row and 3 th column element, value is:  14
this is 1 th row and 3 th column element, value is:  24
this is 2 th row and 3 th column element, value is:  34


# Datatypes with memory size 

In [48]:
ex1=np.array([11,21])     #Python assigns the datatype
print(ex1.dtype)

int32


In [49]:
ex2=np.array([11.0,21.0])      #Python assigns the datatype
print(ex2.dtype)

float64


In [50]:
ex3=np.array([11,21],dtype=np.int64)    #we can also assign data types
print(ex3.dtype)

int64


In [51]:
ex4=np.array([11,12,13],dtype=np.float64)  #we can force integer into the float check output
print(ex4.dtype)
ex4

float64


array([11., 12., 13.])

In [52]:
 ex5=np.array([11.6,12.2,13.4],dtype=np.int32)  #we can force float into the integer check output
print(ex5.dtype)
ex5           

int32


array([11, 12, 13])

# Arithmatic operations in Numpy

In [53]:
x=np.array([[23,24,25],[33,34,35]],dtype=np.int)
y=np.array([[11,12,13],[41,42,43]],dtype=np.float64)
print(x)
print()
print(y)

[[23 24 25]
 [33 34 35]]

[[11. 12. 13.]
 [41. 42. 43.]]


<ipython-input-53-436ae7b8bafc>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x=np.array([[23,24,25],[33,34,35]],dtype=np.int)


In [87]:
print(x  +  y)
print()
print(np.add(x,y))

[[34. 36. 38.]
 [74. 76. 78.]]

[[34. 36. 38.]
 [74. 76. 78.]]


In [55]:
print(x  *  y)
print()
print(np.multiply(x,y))

[[ 253.  288.  325.]
 [1353. 1428. 1505.]]

[[ 253.  288.  325.]
 [1353. 1428. 1505.]]


In [56]:
print("x: ",x)
print("Y: ",y)
print()
print(x   -   y)
print()
print(np.subtract(x,y))

x:  [[23 24 25]
 [33 34 35]]
Y:  [[11. 12. 13.]
 [41. 42. 43.]]

[[12. 12. 12.]
 [-8. -8. -8.]]

[[12. 12. 12.]
 [-8. -8. -8.]]


In [57]:
print("x: ",x)
print("Y: ",y)
print()
print(x   /   y)
print()
print(np.divide(x,y))

x:  [[23 24 25]
 [33 34 35]]
Y:  [[11. 12. 13.]
 [41. 42. 43.]]

[[2.09090909 2.         1.92307692]
 [0.80487805 0.80952381 0.81395349]]

[[2.09090909 2.         1.92307692]
 [0.80487805 0.80952381 0.81395349]]


In [58]:
print(np.sqrt(x))

[[4.79583152 4.89897949 5.        ]
 [5.74456265 5.83095189 5.91607978]]


In [59]:
print(np.exp(x))

[[9.74480345e+09 2.64891221e+10 7.20048993e+10]
 [2.14643580e+14 5.83461743e+14 1.58601345e+15]]


# Mean & Median

In [60]:
#setup a random 2 x 5 matrix
arr=10 * np.random.randn(2,5)
print(arr)

[[ 0.4773796   4.73646084 -3.9740467  -7.43185083 -9.79579583]
 [ 3.59980637 23.85869182 -8.48051668  3.11746173  5.25657566]]


In [61]:
print(arr.mean())      # compute mean for all elements

1.1364165970925033


In [62]:
print(arr.mean(axis= 1))      #compute mean for all rows

[-3.19757058  5.47040378]


In [63]:
print(arr.mean(axis= 0))       #compute mean for all columns

[ 2.03859298 14.29757633 -6.22728169 -2.15719455 -2.26961009]


In [64]:
print(arr.sum())        # compute sum of all elemens in matrix

11.364165970925033


In [65]:
print(np.median(arr,axis = 1))    #compute median for all rows here rows are 2

[-3.9740467   3.59980637]


In [66]:
print(np.median(arr,axis = 0))    #compute median for all columns here comlumns are 5

[ 2.03859298 14.29757633 -6.22728169 -2.15719455 -2.26961009]


# Sort function

In [67]:
unsorted = np.random.randn(10)    #create random array contain 10 elements
print(unsorted)

[ 0.80035691 -0.65811865 -0.13574452 -0.29179952  1.48810859 -0.96801835
  0.84818046  1.27630931  1.69599177  0.15262343]


In [68]:
sorted = np.array(unsorted)
sorted.sort()                    #it arrange values in ascending order
print("sorted vector: ",sorted)
print()
print("unsorted vector: ",unsorted)

sorted vector:  [-0.96801835 -0.65811865 -0.29179952 -0.13574452  0.15262343  0.80035691
  0.84818046  1.27630931  1.48810859  1.69599177]

unsorted vector:  [ 0.80035691 -0.65811865 -0.13574452 -0.29179952  1.48810859 -0.96801835
  0.84818046  1.27630931  1.69599177  0.15262343]


In [69]:
unsorted.sort()
unsorted

array([-0.96801835, -0.65811865, -0.29179952, -0.13574452,  0.15262343,
        0.80035691,  0.84818046,  1.27630931,  1.48810859,  1.69599177])

# Unique function

In [77]:
array=np.array([1,2,5,2,4,7,21,2,5,2])
np.unique(array)                               #it will return unique values in array

array([ 1,  2,  4,  5,  7, 21])

# Set operations

In [71]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [72]:
print(np.intersect1d(s1,s2))      #common values in s1 and s2

['bulb' 'chair']


In [73]:
print(np.union1d(s1,s2))          #common and uncommon values of s1 and s2

['bulb' 'chair' 'desk' 'lamp']


In [74]:
print(np.setdiff1d(s1,s2))        #values of s1 that are not in s2

['desk']


In [75]:
print(np.setdiff1d(s2,s1))   #values of s2 that are not in s1

['lamp']


In [76]:
print(np.in1d(s1,s2))    #which elements of s1 is also in s2

[False  True  True]


In [3]:
start=np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
add_rows=np.array([1,0,2])
add_rows


array([1, 0, 2])

In [5]:
y=start + add_rows      #add each row of start using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [4]:

add_col=np.array([[0,1,2,3]])    
add_col=add_col.T              # 'matrix_name.T' used for trasnpose of matrix : converts rows into columns and vice versa
add_col

array([[0],
       [1],
       [2],
       [3]])

In [6]:

start=np.zeros((4,3))
print(start)
x= start + add_col
print(np.add(start,add_col))
x

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [103]:
add_scalar = np.array([1])      # adding scalar : - this will broadcast in both dimensions 
print(start + add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [111]:
array1 = np.array([[12,13,14,15],[21,22,23,24],[31,32,33,34]])
array2 = np.array([1,2,3,4])
print("Array 1 is :\n ",array1)
print("Array 2 is : \n",array2)
print("Sum of both array is :\n",array1 + array2)

Array 1 is :
  [[12 13 14 15]
 [21 22 23 24]
 [31 32 33 34]]
Array 2 is : 
 [1 2 3 4]
Sum of both array is :
 [[13 15 17 19]
 [22 24 26 28]
 [32 34 36 38]]


# Checking time require to process array and list

In [8]:
from numpy import arange       # you can neglect this if numpy is already imported
from timeit import Timer
size = 1000000
timeits =1000



In [130]:
nd_array = arange(size)     # nd_array will get values upto size-1 i.e 1,2,3.......,size-1
print(type(nd_array))

<class 'numpy.ndarray'>


In [131]:
#Timer expects the operation as parameter,
#here we pass nd_array.sum()

timer_numpy = Timer("nd_array.sum()","from __main__ import nd_array")
print("Time taken by numpy ndarray: %f seconds"%
      (timer_numpy.timeit(timeits)/timeits))

Time taken by numpy ndarray: 0.001006 seconds


In [9]:
a_list = list(arange(size))     #list contain 1000000 values
type(a_list)


list

In [5]:
timer_list = Timer("sum(a_list)","from __main__ import a_list")
print("Time taken by list: %f seconds"%
      (timer_list.timeit(timeits)/timeits))              #Array having better time complexity than list

<timeit-src>:6: RuntimeWarning: overflow encountered in long_scalars


Time taken by list: 0.106475 seconds


In [7]:
x = np.array([1,2,3,4])
np.save('save_array',x)             #all elements in x will be saved in save_array
np.load('save_array.npy')           #''Load' : to retrieve elements in save_array

array([1, 2, 3, 4])

In [15]:
x2d = np.array([[1,1],[1,1]])
y2d= np.array([[2,2],[2,2]])

print(x2d)
print("\n",y2d)
print("\n",x2d.dot(y2d))
print()
print(np.dot(x2d,y2d))

[[1 1]
 [1 1]]

 [[2 2]
 [2 2]]

 [[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [14]:
ex1 = np.array([[1,2],[3,4]])
print(ex1)
print(np.dot(x2d,ex1))

[[1 2]
 [3 4]]
[[4 6]
 [4 6]]


In [15]:
a1d = np.array([9,9])
b1d = np.array([10,10])
print(a1d.dot(b1d))
print()
print(np.dot(a1d,b1d))

180

180


In [17]:
    #dot product on array and vector
print(x2d.dot(a1d))  #[9,9] ,  [1,1],[1,1] [1*9+1*9,1*9+1*9] = [18,18]
print()
print(np.dot(x2d,a1d))
    

[18 18]

[18 18]


In [16]:
ex2 = np.array([[11,12],[13,14]])
print(ex2)
print(np.sum(ex2))              #sum of all elements
print(np.sum(ex2,axis =1))      #rowwise sum
print(np.sum(ex2,axis =0))      #columnwise sum

[[11 12]
 [13 14]]
50
[23 27]
[24 26]


In [25]:
x = np.random.randn(8)
y=np.random.randn(8)
print(x)
print(y)
np.maximum(x,y)               #retrun element wise maximum value 

[ 0.11086968  0.82468602 -0.70693098 -0.92815915 -1.18763887 -0.79669943
  0.4736011  -1.73418987]
[ 0.19729417  0.82380191  0.14631034  1.57526594 -0.73608376  0.1197551
 -0.11503263  0.5168954 ]


array([ 0.19729417,  0.82468602,  0.14631034,  1.57526594, -0.73608376,
        0.1197551 ,  0.4736011 ,  0.5168954 ])

In [20]:
arr= np.arange(20)
print(arr)

a=arr.reshape(4,5)               #reshape built 4X5 martrix of arr values
print(a)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [33]:
a.T                          #'T' used for transpose

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [21]:
x_1 = np.array([1,2,3,4,5])
y_1=np.array([11,22,33,44,55])
#where we have true in filter it will print x_1 value and if it is false then print y_1 value
#this is working of .where funtion
filter = np.array([True,False,True,True,False])


In [22]:
out = np.where(filter,x_1,y_1)
print(out)

[ 1 22  3  4 55]


In [23]:
mat = np.random.randn(5,5)
mat

array([[-0.55645831,  0.30373446, -0.80746142, -1.0295092 , -0.18968914],
       [ 0.33977941,  2.08739216,  0.42923099, -1.26171593,  0.4686581 ],
       [-1.65551155, -2.13856002,  0.20953878,  0.4406498 , -0.00406672],
       [-0.15198945, -1.62558661,  1.02047254,  0.39355018,  1.09457253],
       [-0.73304752,  0.09359133, -1.3100316 ,  0.71485926, -1.33807252]])

In [25]:
np.where(mat>0.5,1000,-1)

array([[  -1,   -1,   -1,   -1,   -1],
       [  -1, 1000,   -1,   -1,   -1],
       [  -1,   -1,   -1,   -1,   -1],
       [  -1,   -1, 1000,   -1, 1000],
       [  -1,   -1,   -1, 1000,   -1]])

In [27]:
'''
if mat > 0.5
  replace it with 1000
else
replace it with -1
'''

'\nif mat > 0.5\n  replace it with 1000\nelse\nreplace it with -1\n'

In [28]:
arr_bool = np.array([True,False,True,True,False])

arr_bool.any()                  # it means is any value is True?

True

In [29]:
arr_bool.all()                    #it means is all value is True?

False

In [30]:
y=np.random.normal(size=(1,5))

print(y)

[[ 0.29697575 -0.78167699  1.37477073 -0.85629268  0.66614306]]


In [31]:
z=np.random.randint(low=2,high = 50,size=4)     # integer values
print(z)                                        #low for minimum value and high for maximum value

[ 9 10 38 11]


In [32]:
np.random.permutation(z)     # return re ordered form of z

array([ 9, 38, 11, 10])

In [33]:
np.random.uniform(size=4)   #for uniform distribution


array([0.87686595, 0.8822765 , 0.52940517, 0.93562458])

In [34]:
np.random.normal(size=4)   #for normal distribution

array([ 0.33811374,  1.5504455 , -0.5153913 , -0.4683903 ])

In [41]:
k=np.random.randint(low=2,high=50,size=(2,2))
print(k)
l=np.random.randint(low=2,high=50,size=(2,2))
print(l)

[[42 44]
 [43 16]]
[[25 28]
 [33 41]]


In [42]:
np.vstack((k,l))      #join two matrices vertically

array([[42, 44],
       [43, 16],
       [25, 28],
       [33, 41]])

In [38]:
np.hstack((k,l))               #join two matrices horizontally

array([[26,  7, 26, 27],
       [ 6, 25, 13, 45]])

In [43]:
np.concatenate([k,l],axis = 0)

array([[42, 44],
       [43, 16],
       [25, 28],
       [33, 41]])

In [48]:
np.concatenate([k,l.T],axis = 1)

array([[42, 44, 25, 33],
       [43, 16, 28, 41]])